# Generated by Django 4.0.2 on 2022-06-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
